"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aJztgQI1O01
 */
import { Button } from "@/components/ui/button"
import { CardHeader, Card } from "@/components/ui/card"
import { useQuery } from "convex/react"
import { api } from "../../../convex/_generated/api"

export function SongList() {
  const songs = useQuery(api.songs.list, {});
  return (
    <div className="px-4 md:px-6">
      <div className="flex items-center gap-4 py-4 md:py-6">
        <div className="hidden md:block w-0 h-0 border-r-4 border-gray-100 dark:border-gray-850" />
        <div className="flex-1 min-w-0">
          <h1 className="text-2xl font-semibold tracking-tighter">Music</h1>
        </div>
        <Button size="sm">Upgrade</Button>
      </div>
      <div className="border-b border-gray-200 dark:border-gray-800" />
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-6 my-6">
        {songs?.map(song => (<Card key={song._id}>
          <CardHeader className="p-4">
            <div className="flex items-center gap-4">
              <img
                alt="Album cover"
                className="aspect-square object-cover rounded-lg"
                height={100}
                src="/placeholder.svg"
                width={100}
              />
              <div className="min-w-0">
                <h3 className="font-semibold text-lg md:text-xl">{song.title}</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">by {song.artist}</p>
              </div>
              <Button className="ml-auto" size="sm" variant="outline">
                <span className="sr-only">Play</span>
                <PlayIcon className="w-4 h-4" />
              </Button>
            </div>
          </CardHeader>
        </Card>))}
      </div>
    </div>
  )
}


function PlayIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="5 3 19 12 5 21 5 3" />
    </svg>
  )
}
